[package]
name = "pdfshrink"
version = "0.1.0"
authors = ["Federico Stra <stra.federico@gmail.com>"]
description = "Shrink PDF files using Ghostscript"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
tempdir = "0.3"
